# Health Stats Part 4: Waist 2 Hip Ratios - Pandas Only

<!--- Write an explanation of the Waist To Hips Ratio statistic used by health professionals. Please include an explanation of what it is used for, exactly how it is calculated, and how to interpret the results. Note: Formmatting matters. Make this as professional as you can using Markdown.  --->
<!--- EDIT THIS MARKDOWN CELL--->

Waist-To-Hip Ratio is a measurement used by health professionals to determine if a patient is overweight, and to evaluate whether the extra weight is putting your health at risk. Those who carry more weight around the waist are at higher risk for heart disease, type 2 diabetes, and even premature death.

The Waist-to-Hip Ratio is calculated by taking the waist measurement of the patient, and dividing that by the hip measurement. For accurate measurement, stand up straight, breathe out, and measure the waist at the narrowest part, just above the belly button. Assume your measurement is 28 inches. Next, measure the widest part of your hips. Your measurement is 35 inches. These numbers are then put into the following calculation:

Waist measurement / Hip measurement = 28 / 35 = .8


According to the World Health Organization (WHO), a healthy Waist-To-Hip Ratio is:

0.9 or less for men, and
0.8 or less for women

Ratios less than the guidelines shown above are referred to as "pears". Ratios greater than the guidelines are referred to as "apples".

| Health risk | Women | Men |
| ----------- | ----- | ---|
| Low | 0.80 or lower | 0.95 or lower |
| Moderate | 0.81–0.85 | 0.96–1.0 |
| High | 0.86 or higher | 1.0 or higher |

Healthline (https://www.healthline.com/health/waist-to-hip-ratio)

## Source Data

<!--- Replace the text below with a Markdown bullet list that defines the columns of the CSV file. Be sure to indicate the data type for each column. --->
<!---EDIT THIS MARKDOWN CELL--->
W2H Ratio - Definitions of Columns
- ID | Unique Identifier of Subject in Study | Integer 
- Waist | Waist Measurement in Inches | Integer
- Hip | Hip Measurement in Inches | Integer
- Gender | Self-reported gender of Subject in Study | Character


<img src = 'https://upload.wikimedia.org/wikipedia/commons/3/34/Abdominal_obesity_in_men.jpg' />

| Waist | Hip |
| ------- | ------- |
| 33 inches | 35 inches |

This subject represents an "apple" shape: W2H ratio = .94

$ ratio_{w2h} = \frac{w}{h} $

## Data Import

In [144]:
# Goal: Extract the data from the file

# use proper pandas function to read data from a CSV file to a DataFrame

import pandas as pd
week10file = pd.read_csv('w2h_data.csv')
week10file.head()

   ID  Waist  Hip Gender
0   1     30   32      M
1   2     32   37      M
2   3     30   36      M
3   4     33   39      M
4   5     29   33      M

## Calculations

In [145]:
# Goal: For each row of data calculate and store the w2h_ratio and shape.

# Step 1: Make sure the columns are in correct data types - refer to previous parts for the correct data types
# Waist and hip are integers so we do not need to change anything

# Step 2: calculate the 'W2H_Ratio' column using the 'Waist' and 'Hip' columns

# Step 3: Create the `Shape` column based on the values of the `W2H_Ratio` column - refer to previous parts for the logic

In [146]:
# Step 1: Make sure the columns are in correct data types - refer to previous parts for the correct data types
week10file.dtypes #commented out so fewer than 7 rows

ID         int64
Waist      int64
Hip        int64
Gender    object
dtype: object

In [147]:
# Step 2: calculate the 'W2H_Ratio' column using the 'Waist' and 'Hip' columns

In [148]:
week10file['w2h_ratio'] = week10file['Waist']/week10file['Hip']

week10file

    ID  Waist  Hip Gender  w2h_ratio
0    1     30   32      M   0.937500
1    2     32   37      M   0.864865
2    3     30   36      M   0.833333
3    4     33   39      M   0.846154
4    5     29   33      M   0.878788
5    6     32   38      M   0.842105
6    7     33   42      M   0.785714
7    8     30   40      M   0.750000
8    9     30   37      M   0.810811
9   10     32   39      M   0.820513
10  11     24   35      F   0.685714
11  12     25   37      F   0.675676
12  13     24   37      F   0.648649
13  14     22   34      F   0.647059
14  15     26   38      F   0.684211
15  16     26   37      F   0.702703
16  17     25   38      F   0.657895
17  18     26   37      F   0.702703
18  19     28   40      F   0.700000
19  20     23   35      F   0.657143

In [149]:
# Step 3: Create the `Shape` column based on the values of the `W2H_Ratio` column - refer to previous parts for the logic

week10file['Shape']="Pear"
week10file.loc[(week10file['Gender'] == 'M') & (week10file['w2h_ratio'] > 0.9) | (week10file['Gender'] == 'F') & (week10file['w2h_ratio'] > 0.8), 'Shape'] = 'Apple'
#week10file.loc[(week10file['Gender'] == 'M') & (week10file['w2h_ratio'] <= 0.9) | (week10file['Gender'] == 'F') & (week10file['w2h_ratio'] <= 0.8), 'Shape'] = 'Pear'
                                  
       
week10file

    ID  Waist  Hip Gender  w2h_ratio  Shape
0    1     30   32      M   0.937500  Apple
1    2     32   37      M   0.864865   Pear
2    3     30   36      M   0.833333   Pear
3    4     33   39      M   0.846154   Pear
4    5     29   33      M   0.878788   Pear
5    6     32   38      M   0.842105   Pear
6    7     33   42      M   0.785714   Pear
7    8     30   40      M   0.750000   Pear
8    9     30   37      M   0.810811   Pear
9   10     32   39      M   0.820513   Pear
10  11     24   35      F   0.685714   Pear
11  12     25   37      F   0.675676   Pear
12  13     24   37      F   0.648649   Pear
13  14     22   34      F   0.647059   Pear
14  15     26   38      F   0.684211   Pear
15  16     26   37      F   0.702703   Pear
16  17     25   38      F   0.657895   Pear
17  18     26   37      F   0.702703   Pear
18  19     28   40      F   0.700000   Pear
19  20     23   35      F   0.657143   Pear

## Output

In [150]:
# Goal: pretty print the rows as an HTML table
week10file
# Display the complete DF

# Save the DF to a file './complete_w2h.csv'

    ID  Waist  Hip Gender  w2h_ratio  Shape
0    1     30   32      M   0.937500  Apple
1    2     32   37      M   0.864865   Pear
2    3     30   36      M   0.833333   Pear
3    4     33   39      M   0.846154   Pear
4    5     29   33      M   0.878788   Pear
5    6     32   38      M   0.842105   Pear
6    7     33   42      M   0.785714   Pear
7    8     30   40      M   0.750000   Pear
8    9     30   37      M   0.810811   Pear
9   10     32   39      M   0.820513   Pear
10  11     24   35      F   0.685714   Pear
11  12     25   37      F   0.675676   Pear
12  13     24   37      F   0.648649   Pear
13  14     22   34      F   0.647059   Pear
14  15     26   38      F   0.684211   Pear
15  16     26   37      F   0.702703   Pear
16  17     25   38      F   0.657895   Pear
17  18     26   37      F   0.702703   Pear
18  19     28   40      F   0.700000   Pear
19  20     23   35      F   0.657143   Pear

In [151]:
# Display the complete DF
print(week10file)

    ID  Waist  Hip Gender  w2h_ratio  Shape
0    1     30   32      M   0.937500  Apple
1    2     32   37      M   0.864865   Pear
2    3     30   36      M   0.833333   Pear
3    4     33   39      M   0.846154   Pear
4    5     29   33      M   0.878788   Pear
5    6     32   38      M   0.842105   Pear
6    7     33   42      M   0.785714   Pear
7    8     30   40      M   0.750000   Pear
8    9     30   37      M   0.810811   Pear
9   10     32   39      M   0.820513   Pear
10  11     24   35      F   0.685714   Pear
11  12     25   37      F   0.675676   Pear
12  13     24   37      F   0.648649   Pear
13  14     22   34      F   0.647059   Pear
14  15     26   38      F   0.684211   Pear
15  16     26   37      F   0.702703   Pear
16  17     25   38      F   0.657895   Pear
17  18     26   37      F   0.702703   Pear
18  19     28   40      F   0.700000   Pear
19  20     23   35      F   0.657143   Pear

In [154]:
# Save the DF to a file './complete_w2h.csv'
week10file.to_csv(r'./complete_w2h.csv')

## Lessons Learned

Have you noticed in the previous two parts, how much code we have written? Have you also note how little code we have written in this part, with the help of Pandas? 

This is the reason why we want to use Pandas to handle the data we use for analytics.

In [156]:
#We used so many fewer lines than in Python. We did it in 6 real lines of programming, excluding inport, print, etc. So glad we got it!